### doctors api calls
### Create doctors Item
POST http://localhost:8081/api/v1/doctors HTTP/1.1
Content-Type: application/json

{
    "Name": "MAX6",
    "Specialty": "Surgeon"
}

### Get doctors Item
GET http://localhost:8081/api/v1/doctors/3 HTTP/1.1

### Update doctors Item
PUT http://localhost:8081/api/v1/doctors/1 HTTP/1.1
Content-Type: application/json

{
  "Name": "Max3"
}

### Delete doctors Item
DELETE http://localhost:8081/api/v1/doctors/2 HTTP/1.1
Content-Type: application/json 




### patients api calls
### Create patient Item
POST http://localhost:8081/api/v1/patients HTTP/1.1
Content-Type: application/json

{
    "Name": "John2",
    "Birthdate": "2004/03/25",
    "Gender": "man"
}

### Get patient Item
GET http://localhost:8081/api/v1/patients/2 HTTP/1.1


### Update patient Item
PUT http://localhost:8081/api/v1/patients/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Johny"
}

### Delete patient Item
DELETE http://localhost:8081/api/v1/patients/1 HTTP/1.1
Content-Type: application/json





### appointments api calls
### Create appointment Item
POST http://localhost:8081/api/v1/appointments HTTP/1.1
Content-Type: application/json

{
    "PatientId": "1",
    "DoctorId": "1",
    "Date": "2024/01/05",     
    "StartTime": "02:03:04",
    "EndTime": "03:03:04",
    "Status": "Ok"
}


### Get appointment Item
GET http://localhost:8081/api/v1/appointments/3 HTTP/1.1


### Update appointment Item
PUT http://localhost:8081/api/v1/appointments/3 HTTP/1.1
Content-Type: application/json

{
    "PatientId": "1",
    "DoctorId": "1",
    "Date": "2024/01/05",     
    "StartTime": "02:03:04",
    "EndTime": "03:03:04",
    "Status": "NOT Ok"
}

### Delete appointment Item
DELETE http://localhost:8081/api/v1/appointments/3 HTTP/1.1
Content-Type: application/json
